### ISSUE TITLE
no favicon until i enter edit mode

### ISSUE THREAD

**Issue by hodanli** [imjn/logseq-url-title-tagger#1]
hi,

thanks for the plugin. i experience two different things, i tried to show in the screen cast:

1. i cannot get the favicon until i enter the edit mode
2. when i paste two in a row second one is not processed.

https://github.com/imjn/logseq-url-title-tagger/assets/6535865/6360a984-176e-46f0-845d-0bc5e190c55d

**Comment by imjn** [comment]
@hodanli Hi! Thanks for reporting! Let me fix 👍🏽

**Comment by imjn** [comment]
It might be still a bit janky but [v1.0.1](https://github.com/imjn/logseq-url-title-tagger/releases/tag/v1.0.1) should improve the experience.
